AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  omnidoc
  
  Sample SAM Template for omnidoc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: go1.x
    Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:  
        db_host: '{{resolve:ssm:RDSPGEndpoint:1}}'
        db_user: '{{resolve:ssm:RDSPGDBUser:1}}'
        db_name: '{{resolve:ssm:DMSDBName:2}}'
        db_pass: '{{resolve:ssm:RDSPGDBPass:1}}'
        dms_bucket: '{{resolve:ssm:DMSBucket:1}}'

Resources:
  CreateDocumentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: services/assets/put
      Handler: put
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
      Policies:
        - S3WritePolicy: 
            Effect: Allow
            Action:
            - s3:PutObject
            BucketName: '{{resolve:ssm:DMSBucket:1}}'

  ListDocumentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: services/assets/get
      Handler: get
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
      Policies:
        - S3ReadPolicy: 
            Effect: Allow
            Action:
            - s3:GetObject
            BucketName: '{{resolve:ssm:DMSBucket:1}}'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OmniDocAPI:
    Description: "API Gateway endpoint URL for Prod environment for OmniDoC API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
